# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java app CI with maven

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  Build:
    name: Build
    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@v1
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11.0.4
      - name: Maven Package
        run: mvn package 
      
  Test:
    name: Test - Units & Integrations
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-18.04
    needs: [Build]
    steps:
      - uses: actions/checkout@v1
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11.0.4
      - name: Maven Package
        run: mvn -B clean package -DskipTests
      - name: Maven Verify
        run: mvn -B clean verify -Pintegration-test

  Sonar:
    name: Test - SonarCloud Scan
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-18.04
    needs: [Build]
    steps:
      - uses: actions/checkout@v1
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11.0.4
      - name: SonarCloud Scan
        run: mvn -B clean verify -Psonar -Dsonar.login=${{ secrets.SONAR_TOKEN }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  DeployWIP:
    name: Deploy to WIP 
    if: github.event_name == 'pull_request'
    needs: [Build, Sonar,Test]
    runs-on: ubuntu-latest
    environment: 
      name: WIP
      #url: 'http://www.myapp.com'
    steps:
      - name: Deploy
        run: echo I am deploying to WIP!!!
  
  DeployStaging:
    name: Deploy to STAGING 
    if: github.event.ref == 'refs/heads/master'
    needs: [Build]
    runs-on: ubuntu-latest
    environment: 
      name: Staging
      #url: 'http://www.myapp.com'
    steps:
      - name: Deploy
        run: echo I am deploying to staging!!!
  
  DeployProduction:
    name: Deploy to Production 
    needs: [DeployStaging]
    runs-on: ubuntu-latest
    environment: 
      name: Production
      #url: 'http://www.myapp.com'
    steps:
      - name: Deploy
        run: echo I am deploying to Production!!!
